version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        restart: always
        volumes:
            - ./src:/var/www/html
            - ./docker/php/supervisord.d:/etc/supervisord.d
            - ./docker/php/supervisord.conf:/etc/supervisord.conf
        entrypoint: ["/usr/bin/supervisord", "-n", "-c",  "/etc/supervisord.conf"]

    web_server:
        image: nginx:alpine3.19
        restart: always
        ports:
            - ${APP_PORT:-80}:80
        volumes:
            - ./src:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

    database:
        image: mysql:latest
        volumes:
            - db-course-store:/var/lib/mysql
        restart: always
        ports:
            - ${DB_PORT:-33062}:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
            MYSQL_DATABASE: ${DB_DATABASE:-example}
            MYSQL_USER: ${DB_USERNAME:-example}
            MYSQL_PASSWORD: ${DB_PASSWORD:-password}

volumes:
    db-course-store:

