version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
                - ./:/var/www/html
        container_name: app
        ports:
            - ${APP_PORT:-8080}:${APP_PORT-:8080}
    web_server:
        image: nginx:alpine3.19
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

    database:
        image: mysql:latest
        volumes:
            - db-course-store:/var/lib/mysql
        restart: unless-stopped
        ports:
            - 33062:${DB_PORT:-3306}
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
            MYSQL_DATABASE: ${DB_DATABASE:-example}
            MYSQL_USER: ${DB_USERNAME:-example}
            MYSQL_PASSWORD: ${DB_PASSWORD:-password}

volumes:
    db-course-store:

